# Generated by Django 4.2.2 on 2023-07-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_student_address"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="email",),
        migrations.RemoveField(model_name="student", name="file",),
        migrations.RemoveField(model_name="student", name="image",),
        migrations.RemoveField(model_name="student", name="phone",),
    ]
